/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#882000",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#1c1b1b",
        "secondary-container": "#fdbb12",
        "on-primary-container": "#858383",
        "on-tertiary": "#ffffff",
        "primary-container": "#1c1b1b",
        "outline-variant": "#c4c7c7",
        "surface-container-low": "#f4f3f1",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e3e2e0",
        "surface-container": "#efeeec",
        "surface-bright": "#faf9f7",
        "on-secondary-container": "#6c4d00",
        "on-tertiary-container": "#e65127",
        "primary": "#000000",
        "secondary-fixed": "#ffdea4",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e3e2e0",
        "secondary": "#7b5900",
        "surface": "#faf9f7",
        "surface-dim": "#dadad8",
        "on-background": "#1a1c1b",
        "on-error": "#ffffff",
        "tertiary-fixed": "#ffdbd1",
        "on-primary-fixed-variant": "#474746",
        "inverse-primary": "#c8c6c5",
        "surface-tint": "#5f5e5e",
        "on-surface": "#1a1c1b",
        "tertiary-container": "#3b0900",
        "on-tertiary-fixed": "#3b0900",
        "error": "#ba1a1a",
        "surface-container-high": "#e9e8e6",
        "inverse-surface": "#2f3130",
        "inverse-on-surface": "#f1f1ef",
        "background": "#faf9f7",
        "tertiary-fixed-dim": "#ffb5a1",
        "tertiary": "#000000",
        "secondary-fixed-dim": "#fdbb12",
        "primary-fixed": "#e5e2e1",
        "on-surface-variant": "#444748",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#5d4200",
        "primary-fixed-dim": "#c8c6c5",
        "on-secondary-fixed": "#261900",
        "outline": "#747878",
        "on-secondary": "#ffffff",
        "ink": "#161616",
        "charcoal": "#3a3a3a",
        "signature-gold": "#f5b400",
        "success-green": "#1e8a5f",
        "danger-red": "#c4432b",
        "warning-amber": "#c77800"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.375rem",
        "md": "0.5rem",
        "lg": "0.75rem",
        "xl": "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "64px",
        "container-max": "1440px",
        "margin-mobile": "20px",
        "gutter": "24px",
        "unit": "8px"
      },
      fontFamily: {
        "display-md": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["Space Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Space Grotesk", "sans-serif"],
        "kpi-metric": ["Space Grotesk", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-md": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "kpi-metric": ["40px", { "lineHeight": "1", "letterSpacing": "-0.03em", "fontWeight": "700" }],
        "headline-sm": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "1.4", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
}
